"""
forecast.py — Ensemble price forecast (Linear Regression + Bollinger + Forward P/E).
"""

import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

DISCLAIMER = (
    "⚠️ MODEL-BASED ESTIMATES ONLY — NOT FINANCIAL ADVICE. "
    "Forecasts are generated by quantitative models and carry inherent uncertainty. "
    "Past performance does not guarantee future results. "
    "Always consult a licensed financial advisor before making investment decisions."
)


def _linear_forecast(series: pd.Series, days: int) -> float:
    s = series.dropna().tail(252)
    x = np.arange(len(s)).reshape(-1, 1)
    m = LinearRegression().fit(x, s.values)
    capped_days = min(days, 126)
    return float(m.predict([[len(s) + capped_days]])[0])


def _bollinger_forecast(series: pd.Series) -> dict:
    c   = series.dropna()
    mid = c.rolling(20).mean().iloc[-1]
    std = c.rolling(20).std().iloc[-1]
    cur = c.iloc[-1]
    upper, lower = mid + 2 * std, mid - 2 * std
    base = mid + (cur - mid) * 0.4 if cur > mid else mid - (mid - cur) * 0.4
    return {"bull": upper, "base": base, "bear": lower}


def _pe_forecast(info: dict) -> dict:
    fpe = info.get("forwardPE")
    eps = info.get("trailingEps")
    if not fpe or not eps:
        return {}
    gr = info.get("earningsGrowth") or 0.08
    eps6, eps12 = eps * (1 + gr * 0.5), eps * (1 + gr)
    return {
        "6m":  {"bull": eps6  * fpe * 1.15, "base": eps6  * fpe, "bear": eps6  * fpe * 0.85},
        "12m": {"bull": eps12 * fpe * 1.15, "base": eps12 * fpe, "bear": eps12 * fpe * 0.85},
        "eps_growth_used": round(gr * 100, 1),
        "pe_used": fpe,
    }


def run_forecast(price_history: pd.DataFrame, info: dict, fundamental_data: dict) -> dict:
    result = {"disclaimer": DISCLAIMER, "6m": {}, "12m": {}, "confidence": "Low",
              "assumptions": {}, "chart": None}

    close = price_history["Close"].dropna()
    if len(close) < 60:
        result["error"] = "Insufficient price history for forecast."
        return result

    cur = float(close.iloc[-1])
    lr6, lr12 = _linear_forecast(close, 126), _linear_forecast(close, 252)
    bb   = _bollinger_forecast(close)
    pe   = _pe_forecast(info)

    ann_vol = close.pct_change().dropna().std() * np.sqrt(252)
    v6, v12 = ann_vol * np.sqrt(0.5), ann_vol

    def ensemble(lr_v, bb_v, pe_v, vol):
        if pe_v:
            base = 0.40 * lr_v + 0.30 * bb_v + 0.30 * pe_v
        else:
            base = 0.55 * lr_v + 0.45 * bb_v
        return {
            "bull": round(base * (1 + vol * 0.8), 2),
            "base": round(base, 2),
            "bear": round(base * (1 - vol * 0.8), 2),
        }

    result["6m"]  = ensemble(lr6,  bb["base"], pe.get("6m",  {}).get("base"), v6)
    result["12m"] = ensemble(lr12, bb["base"], pe.get("12m", {}).get("base"), v12)

    bb_width_pct = (bb["bull"] - bb["bear"]) / bb["base"] if bb["base"] != 0 else 0
    spread = (max(lr6, bb["base"]) - min(lr6, bb["base"])) / cur * 100
    vol_penalty = bb_width_pct * 50  # scale BB width into percentage points
    adjusted_spread = spread + vol_penalty
    result["confidence"] = "High" if adjusted_spread < 10 else "Medium" if adjusted_spread < 25 else "Low"

    result["assumptions"] = {
        "Current Price":      f"{cur:.2f}",
        "Annual Volatility":  f"{ann_vol*100:.1f}%",
        "EPS Growth Rate":    f"{pe.get('eps_growth_used', 'N/A')}%",
        "Forward P/E Used":   f"{pe.get('pe_used', 'N/A')}",
        "Models":             "LR 40% + BB 30% + P/E 30%" if pe else "LR 55% + BB 45%",
    }

    # Forecast chart
    today  = pd.Timestamp.today()
    dates  = [today, today + pd.DateOffset(months=6), today + pd.DateOffset(months=12)]
    bulls  = [cur, result["6m"]["bull"],  result["12m"]["bull"]]
    bases  = [cur, result["6m"]["base"],  result["12m"]["base"]]
    bears  = [cur, result["6m"]["bear"],  result["12m"]["bear"]]

    fig = go.Figure()
    six_months_ago = close.index[-1] - pd.DateOffset(months=6)
    hist6 = close[close.index >= six_months_ago]
    fig.add_trace(go.Scatter(x=hist6.index, y=hist6.values,
                              name="Historical", line=dict(color="#94a3b8", width=2)))
    fig.add_trace(go.Scatter(x=dates + dates[::-1], y=bulls + bears[::-1],
                              fill="toself", fillcolor="rgba(0,212,170,0.08)",
                              line=dict(color="rgba(0,0,0,0)"), name="Range"))
    for vals, color, name, dash in [
        (bulls, "#26a69a", "Bull",  "dot"),
        (bases, "#00d4aa", "Base",  "solid"),
        (bears, "#ef5350", "Bear",  "dot"),
    ]:
        fig.add_trace(go.Scatter(x=dates, y=vals, name=name, mode="lines+markers",
                                  line=dict(color=color, width=2, dash=dash),
                                  marker=dict(size=8)))
    fig.add_hline(y=cur, line_color="#64748b", line_dash="dash", line_width=1,
                  annotation_text=f"Now: {cur:.2f}")
    fig.update_layout(
        title="12-Month Forecast — Bull / Base / Bear",
        height=420,
        plot_bgcolor="#0f1117", paper_bgcolor="#0f1117",
        font=dict(color="#e8eaf0", size=11),
        xaxis=dict(gridcolor="#1e2433"), yaxis=dict(gridcolor="#1e2433"),
        legend=dict(orientation="h", y=1.02, x=0, bgcolor="rgba(0,0,0,0)"),
        margin=dict(l=10, r=10, t=50, b=10),
    )
    result["chart"] = fig
    return result
